eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    driver: com.mysql.jdbc.Driver
    username: root
    password: root
    initialization-mode: always
  jpa:
    generate-ddl: false
    hibernate:
      show-sql: true
      cache:
        use_query_cache: false
        use_second_level_cache: false
    properties:
      hibernate:
        connection:
          charSet=UTF-8
  http:
    multipart:
      max-file-size: 1500KB
      max-request-size: 1500KB

management:
  endpoints:
    web:
      exposure:
        include: "*"